apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "springboot-demoweb.fullname" . }}
  labels:
    app: {{ template "springboot-demoweb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "springboot-demoweb.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "192.168.99.102:5002/karigartest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            
            - containerPort: {{ .Values.service.internalPort }}
          resources:
            {{ toYaml .Values.resources | indent 12 }}
              {{- if .Values.nodeSelector }}
                nodeSelector:
            {{ toYaml .Values.nodeSelector | indent 8 }}
              {{- end}}
